import React from 'react';
import { Box, Button } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import PageHeader from '../../components/PageHeader';
import IntakeFormsListPage from '../customApplications/IntakeFormsListPage';

export default function ApplicationCustomizationIntakeFormsPage() {
  const navigate = useNavigate();

  return (
    <Box>
      <PageHeader
        title="Intake Forms"
        subtitle="Manage intake forms for custom applications. These forms are generated by asking questions from start to end in the Website Customization navigation."
      />
      <IntakeFormsListPage />
    </Box>
  );
}
